coverage:
  status:
    project:
      default:
        enabled: yes
        target: 90%
    patch:
      default:
        enabled: yes
        target: 55%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false