name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches:
    - '**'

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  python-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python-version: ['3.12']
        toxenv: [py312-django32, py312-django42]

    steps:
      - uses: actions/checkout@v4

      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}  
      
      - name: tox install
        run: pip install tox

      - name: Run Tests
        env:
          TOXENV: ${{ matrix.toxenv }}
        run: tox
        
      - name: Upload coverage to CodeCov
        if: matrix.python-version == '3.12' && matrix.toxenv == 'py312-django42'
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: false

      - name: Run Integration Tests 
        run: |
            cd ..
            git clone https://github.com/openedx/devstack
            cd devstack
            sed -i 's/:cached//g' ./docker-compose-host.yml
            make dev.clone.https
            DEVSTACK_WORKSPACE=$PWD/.. docker-compose -f docker-compose.yml -f docker-compose-host.yml run -v $PWD/../edx-sga:/edx-sga lms /edx-sga/run_devstack_integration_tests.sh

      - name: Upload coverage to CodeCov
        if: matrix.python-version == '3.12' && matrix.toxenv == 'py312-django42'
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: false
